/**
 * Constants for the FixTogether application
 */

const ROLES = {
  OWNER: 'owner',
  TECHNICIAN: 'technician',
  ORGANIZATION: 'organization',
  ADMIN: 'admin',
};

const ACCOUNT_STATUS = {
  ACTIVE: 'active',
  SUSPENDED: 'suspended',
  DEACTIVATED: 'deactivated',
  PENDING_VERIFICATION: 'pending_verification',
};

const ORGANIZATION_TYPES = {
  REPAIR_GROUP: 'repair_group',
  DONATION_ORG: 'donation_organization',
  RECYCLING_FACILITY: 'recycling_facility',
};

const VERIFICATION_STATUS = {
  NOT_SUBMITTED: 'not_submitted',
  PENDING: 'pending',
  MORE_INFO_NEEDED: 'more_info_needed',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  EXPIRED: 'expired',
};

const JOB_PART_STATUS = {
  REQUIRED: 'required',
  SEARCHING: 'searching',
  ORDERED: 'ordered',
  IN_TRANSIT: 'in_transit',
  RECEIVED: 'received',
  INSTALLED: 'installed',
  RETURNED: 'returned',
  UNAVAILABLE: 'unavailable',
};

const REPAIR_JOB_STATUS = {
  PENDING_INSPECTION: 'pending_inspection',
  INSPECTING: 'inspecting',
  AWAITING_APPROVAL: 'awaiting_approval',
  WAITING_FOR_PARTS: 'waiting_for_parts',
  IN_PROGRESS: 'in_progress',
  QUALITY_CHECK: 'quality_check',
  READY_FOR_COLLECTION: 'ready_for_collection',
  COMPLETED: 'completed',
  UNSUCCESSFUL: 'unsuccessful',
  CANCELLED: 'cancelled',
  DISPUTED: 'disputed',
};

/**
 * Permitted status transitions for repair jobs.
 */
const REPAIR_JOB_TRANSITIONS = {
  [REPAIR_JOB_STATUS.PENDING_INSPECTION]: [
    REPAIR_JOB_STATUS.INSPECTING,
    REPAIR_JOB_STATUS.CANCELLED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.INSPECTING]: [
    REPAIR_JOB_STATUS.AWAITING_APPROVAL,
    REPAIR_JOB_STATUS.WAITING_FOR_PARTS,
    REPAIR_JOB_STATUS.IN_PROGRESS,
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.CANCELLED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.AWAITING_APPROVAL]: [
    REPAIR_JOB_STATUS.WAITING_FOR_PARTS,
    REPAIR_JOB_STATUS.IN_PROGRESS,
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.CANCELLED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.WAITING_FOR_PARTS]: [
    REPAIR_JOB_STATUS.IN_PROGRESS,
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.CANCELLED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.IN_PROGRESS]: [
    REPAIR_JOB_STATUS.QUALITY_CHECK,
    REPAIR_JOB_STATUS.WAITING_FOR_PARTS,
    REPAIR_JOB_STATUS.AWAITING_APPROVAL,
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.CANCELLED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.QUALITY_CHECK]: [
    REPAIR_JOB_STATUS.READY_FOR_COLLECTION,
    REPAIR_JOB_STATUS.IN_PROGRESS, // failed QA -> rework
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.READY_FOR_COLLECTION]: [
    REPAIR_JOB_STATUS.COMPLETED,
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.COMPLETED]: [
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.UNSUCCESSFUL]: [
    REPAIR_JOB_STATUS.DISPUTED,
  ],
  [REPAIR_JOB_STATUS.CANCELLED]: [],
  [REPAIR_JOB_STATUS.DISPUTED]: [
    REPAIR_JOB_STATUS.COMPLETED,
    REPAIR_JOB_STATUS.UNSUCCESSFUL,
    REPAIR_JOB_STATUS.CANCELLED,
  ],
};

const ITEM_CONDITION = {
  NEW: 'new',
  GOOD: 'good',
  FAIR: 'fair',
  POOR: 'poor',
  BROKEN: 'broken',
  FOR_PARTS: 'for_parts',
};

const ITEM_STATUS = {
  ACTIVE: 'active',
  IN_REPAIR: 'in_repair',
  DONATED: 'donated',
  PARTS_RECOVERED: 'parts_recovered',
  RECYCLED: 'recycled',
  REMOVED: 'removed',
};

const PATHWAYS = {
  REPAIR: 'repair',
  REFURBISHMENT: 'refurbishment',
  DONATION: 'donation',
  PARTS: 'parts',
  RECYCLING: 'recycling',
};

const REPAIR_REQUEST_STATUS = {
  DRAFT: 'draft',
  AWAITING_AI_ANALYSIS: 'awaiting_ai_analysis',
  AWAITING_OWNER_REVIEW: 'awaiting_owner_review',
  AWAITING_CLARIFICATION: 'awaiting_clarification',
  PUBLISHED: 'published',
  MATCHING_TECHNICIANS: 'matching_technicians',
  AWAITING_QUOTATIONS: 'awaiting_quotations',
  QUOTATIONS_RECEIVED: 'quotations_received',
  QUOTATION_ACCEPTED: 'quotation_accepted',
  APPOINTMENT_SCHEDULED: 'appointment_scheduled',
  UNDER_INSPECTION: 'under_inspection',
  AWAITING_OWNER_APPROVAL: 'awaiting_owner_approval',
  WAITING_FOR_PARTS: 'waiting_for_parts',
  REPAIR_IN_PROGRESS: 'repair_in_progress',
  QUALITY_CHECK: 'quality_check',
  READY_FOR_COLLECTION: 'ready_for_collection',
  COMPLETED: 'completed',
  REPAIR_UNSUCCESSFUL: 'repair_unsuccessful',
  DONATION_OFFERED: 'donation_offered',
  PARTS_REUSE_APPROVED: 'parts_reuse_approved',
  SENT_FOR_RECYCLING: 'sent_for_recycling',
  CANCELLED: 'cancelled',
  DISPUTED: 'disputed',
};

/**
 * Valid status transitions for repair requests.
 * Maps current status -> array of allowed next statuses.
 */
const REPAIR_STATUS_TRANSITIONS = {
  [REPAIR_REQUEST_STATUS.DRAFT]: [
    REPAIR_REQUEST_STATUS.AWAITING_AI_ANALYSIS,
    REPAIR_REQUEST_STATUS.PUBLISHED, // manual fallback
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.AWAITING_AI_ANALYSIS]: [
    REPAIR_REQUEST_STATUS.AWAITING_OWNER_REVIEW,
    REPAIR_REQUEST_STATUS.PUBLISHED, // AI failure fallback
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.AWAITING_OWNER_REVIEW]: [
    REPAIR_REQUEST_STATUS.AWAITING_CLARIFICATION,
    REPAIR_REQUEST_STATUS.PUBLISHED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.AWAITING_CLARIFICATION]: [
    REPAIR_REQUEST_STATUS.PUBLISHED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.PUBLISHED]: [
    REPAIR_REQUEST_STATUS.MATCHING_TECHNICIANS,
    REPAIR_REQUEST_STATUS.AWAITING_QUOTATIONS,
    REPAIR_REQUEST_STATUS.DONATION_OFFERED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.MATCHING_TECHNICIANS]: [
    REPAIR_REQUEST_STATUS.AWAITING_QUOTATIONS,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.AWAITING_QUOTATIONS]: [
    REPAIR_REQUEST_STATUS.QUOTATIONS_RECEIVED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.QUOTATIONS_RECEIVED]: [
    REPAIR_REQUEST_STATUS.QUOTATION_ACCEPTED,
    REPAIR_REQUEST_STATUS.AWAITING_QUOTATIONS,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.QUOTATION_ACCEPTED]: [
    REPAIR_REQUEST_STATUS.APPOINTMENT_SCHEDULED,
    REPAIR_REQUEST_STATUS.CANCELLED,
    REPAIR_REQUEST_STATUS.DISPUTED,
  ],
  [REPAIR_REQUEST_STATUS.APPOINTMENT_SCHEDULED]: [
    REPAIR_REQUEST_STATUS.UNDER_INSPECTION,
    REPAIR_REQUEST_STATUS.QUOTATION_ACCEPTED, // reschedule
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.UNDER_INSPECTION]: [
    REPAIR_REQUEST_STATUS.AWAITING_OWNER_APPROVAL,
    REPAIR_REQUEST_STATUS.REPAIR_IN_PROGRESS,
    REPAIR_REQUEST_STATUS.REPAIR_UNSUCCESSFUL,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.AWAITING_OWNER_APPROVAL]: [
    REPAIR_REQUEST_STATUS.REPAIR_IN_PROGRESS,
    REPAIR_REQUEST_STATUS.WAITING_FOR_PARTS,
    REPAIR_REQUEST_STATUS.CANCELLED,
    REPAIR_REQUEST_STATUS.DISPUTED,
  ],
  [REPAIR_REQUEST_STATUS.WAITING_FOR_PARTS]: [
    REPAIR_REQUEST_STATUS.REPAIR_IN_PROGRESS,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.REPAIR_IN_PROGRESS]: [
    REPAIR_REQUEST_STATUS.QUALITY_CHECK,
    REPAIR_REQUEST_STATUS.WAITING_FOR_PARTS,
    REPAIR_REQUEST_STATUS.REPAIR_UNSUCCESSFUL,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.QUALITY_CHECK]: [
    REPAIR_REQUEST_STATUS.READY_FOR_COLLECTION,
    REPAIR_REQUEST_STATUS.REPAIR_IN_PROGRESS, // rework
    REPAIR_REQUEST_STATUS.REPAIR_UNSUCCESSFUL,
  ],
  [REPAIR_REQUEST_STATUS.READY_FOR_COLLECTION]: [
    REPAIR_REQUEST_STATUS.COMPLETED,
    REPAIR_REQUEST_STATUS.DISPUTED,
  ],
  [REPAIR_REQUEST_STATUS.COMPLETED]: [
    REPAIR_REQUEST_STATUS.DISPUTED,
  ],
  [REPAIR_REQUEST_STATUS.REPAIR_UNSUCCESSFUL]: [
    REPAIR_REQUEST_STATUS.DONATION_OFFERED,
    REPAIR_REQUEST_STATUS.PARTS_REUSE_APPROVED,
    REPAIR_REQUEST_STATUS.SENT_FOR_RECYCLING,
    REPAIR_REQUEST_STATUS.DISPUTED,
  ],
  [REPAIR_REQUEST_STATUS.DONATION_OFFERED]: [
    REPAIR_REQUEST_STATUS.COMPLETED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
  [REPAIR_REQUEST_STATUS.PARTS_REUSE_APPROVED]: [
    REPAIR_REQUEST_STATUS.COMPLETED,
  ],
  [REPAIR_REQUEST_STATUS.SENT_FOR_RECYCLING]: [
    REPAIR_REQUEST_STATUS.COMPLETED,
  ],
  [REPAIR_REQUEST_STATUS.CANCELLED]: [],
  [REPAIR_REQUEST_STATUS.DISPUTED]: [
    REPAIR_REQUEST_STATUS.COMPLETED,
    REPAIR_REQUEST_STATUS.CANCELLED,
  ],
};

const QUOTATION_STATUS = {
  PENDING: 'pending',
  SUBMITTED: 'submitted',
  REVISED: 'revised',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  WITHDRAWN: 'withdrawn',
  EXPIRED: 'expired',
  NOT_SELECTED: 'not_selected',
};

const APPOINTMENT_STATUS = {
  SCHEDULED: 'scheduled',
  CONFIRMED: 'confirmed',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  RESCHEDULED: 'rescheduled',
  NO_SHOW: 'no_show',
};

const APPOINTMENT_TYPE = {
  INSPECTION: 'inspection',
  REPAIR: 'repair',
  PICKUP: 'pickup',
  DROPOFF: 'dropoff',
};

const DONATION_STATUS = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  PUBLISHED: 'published',
  MATCHED: 'matched',
  UNDER_REVIEW: 'under_review',
  ACCEPTED: 'accepted',
  HANDOVER_SCHEDULED: 'handover_scheduled',
  PICKUP_SCHEDULED: 'pickup_scheduled',
  IN_TRANSIT: 'in_transit',
  AWAITING_DROPOFF: 'awaiting_dropoff',
  RECEIVED: 'received',
  INSPECTION_PENDING: 'inspection_pending',
  INSPECTED: 'inspected',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  REJECTED: 'rejected',
  REJECTED_AFTER_INSPECTION: 'rejected_after_inspection',
  CANCELLED: 'cancelled',
};

const COMMUNITY_NEED_STATUS = {
  DRAFT: 'draft',
  PUBLISHED: 'published',
  PARTIALLY_MATCHED: 'partially_matched',
  PARTIALLY_FULFILLED: 'partially_fulfilled',
  FULFILLED: 'fulfilled',
  CLOSED: 'closed',
  EXPIRED: 'expired',
  CANCELLED: 'cancelled',
};

const INSPECTION_OUTCOMES = {
  ACCEPTED_WORKING: 'accepted_working',
  ACCEPTED_REFURBISHMENT: 'accepted_for_refurbishment',
  ACCEPTED_PARTS: 'accepted_for_parts',
  ACCEPTED_RECYCLING: 'accepted_for_recycling',
  REJECTED_SAFETY: 'rejected_safety',
  REJECTED_CONDITION_MISMATCH: 'rejected_condition_mismatch',
  MORE_INFO_REQUIRED: 'more_info_required',
};

const PROCESSING_OUTCOMES = {
  REDISTRIBUTED: 'redistributed',
  REFURBISHED: 'refurbished',
  SALVAGED_PARTS: 'salvaged_parts',
  RESPONSIBLY_RECYCLED: 'responsibly_recycled',
  REJECTED_AFTER_INSPECTION: 'rejected_after_inspection',
};

const HUB_STATUS = {
  ACTIVE: 'active',
  TEMPORARILY_CLOSED: 'temporarily_closed',
  AT_CAPACITY: 'at_capacity',
  APPOINTMENT_ONLY: 'appointment_only',
  INACTIVE: 'inactive',
};

const DONATION_TRANSITIONS = {
  [DONATION_STATUS.DRAFT]: [
    DONATION_STATUS.SUBMITTED,
    DONATION_STATUS.PUBLISHED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.SUBMITTED]: [
    DONATION_STATUS.UNDER_REVIEW,
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.REJECTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.PUBLISHED]: [
    DONATION_STATUS.MATCHED,
    DONATION_STATUS.UNDER_REVIEW,
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.REJECTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.MATCHED]: [
    DONATION_STATUS.UNDER_REVIEW,
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.REJECTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.UNDER_REVIEW]: [
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.REJECTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.ACCEPTED]: [
    DONATION_STATUS.HANDOVER_SCHEDULED,
    DONATION_STATUS.PICKUP_SCHEDULED,
    DONATION_STATUS.IN_TRANSIT,
    DONATION_STATUS.AWAITING_DROPOFF,
    DONATION_STATUS.RECEIVED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.HANDOVER_SCHEDULED]: [
    DONATION_STATUS.IN_TRANSIT,
    DONATION_STATUS.AWAITING_DROPOFF,
    DONATION_STATUS.RECEIVED,
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.PICKUP_SCHEDULED]: [
    DONATION_STATUS.IN_TRANSIT,
    DONATION_STATUS.RECEIVED,
    DONATION_STATUS.ACCEPTED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.IN_TRANSIT]: [
    DONATION_STATUS.RECEIVED,
    DONATION_STATUS.HANDOVER_SCHEDULED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.AWAITING_DROPOFF]: [
    DONATION_STATUS.RECEIVED,
    DONATION_STATUS.HANDOVER_SCHEDULED,
    DONATION_STATUS.CANCELLED,
  ],
  [DONATION_STATUS.RECEIVED]: [
    DONATION_STATUS.INSPECTION_PENDING,
    DONATION_STATUS.INSPECTED,
    DONATION_STATUS.REJECTED_AFTER_INSPECTION,
  ],
  [DONATION_STATUS.INSPECTION_PENDING]: [
    DONATION_STATUS.INSPECTED,
    DONATION_STATUS.PROCESSING,
    DONATION_STATUS.REJECTED_AFTER_INSPECTION,
    DONATION_STATUS.COMPLETED,
  ],
  [DONATION_STATUS.INSPECTED]: [
    DONATION_STATUS.PROCESSING,
    DONATION_STATUS.COMPLETED,
    DONATION_STATUS.REJECTED_AFTER_INSPECTION,
  ],
  [DONATION_STATUS.PROCESSING]: [
    DONATION_STATUS.COMPLETED,
    DONATION_STATUS.REJECTED_AFTER_INSPECTION,
  ],
  [DONATION_STATUS.COMPLETED]: [],
  [DONATION_STATUS.REJECTED]: [],
  [DONATION_STATUS.REJECTED_AFTER_INSPECTION]: [],
  [DONATION_STATUS.CANCELLED]: [],
};

const DISPUTE_STATUS = {
  OPEN: 'open',
  UNDER_REVIEW: 'under_review',
  AWAITING_RESPONSE: 'awaiting_response',
  RESOLVED: 'resolved',
  CLOSED: 'closed',
};

const DISPUTE_CATEGORIES = {
  QUALITY: 'quality',
  COST: 'cost',
  TIMELINE: 'timeline',
  COMMUNICATION: 'communication',
  DAMAGE: 'damage',
  WARRANTY: 'warranty',
  OTHER: 'other',
};

const WARRANTY_STATUS = {
  ACTIVE: 'active',
  EXPIRED: 'expired',
  CLAIMED: 'claimed',
  VOIDED: 'voided',
};

const PART_STATUS = {
  AVAILABLE: 'available',
  RESERVED: 'reserved',
  SOLD: 'sold',
  REMOVED: 'removed',
};

const PART_CONDITION = {
  NEW: 'new',
  TESTED_WORKING: 'tested_working',
  UNTESTED: 'untested',
  DAMAGED: 'damaged',
};

const RISK_LEVEL = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
};

const SERVICE_METHOD = {
  ONSITE: 'onsite',
  PICKUP: 'pickup',
  DROPOFF: 'dropoff',
  REMOTE: 'remote',
};

const NOTIFICATION_TYPES = {
  ACCOUNT_VERIFIED: 'account_verified',
  ACCOUNT_REJECTED: 'account_rejected',
  ACCOUNT_SUSPENDED: 'account_suspended',
  ACCOUNT_RESTORED: 'account_restored',
  REPAIR_REQUEST_PUBLISHED: 'repair_request_published',
  TECHNICIAN_MATCH: 'technician_match',
  QUOTATION_INVITATION: 'quotation_invitation',
  QUOTATION_SUBMITTED: 'quotation_submitted',
  QUOTATION_REVISED: 'quotation_revised',
  QUOTATION_ACCEPTED: 'quotation_accepted',
  QUOTATION_REJECTED: 'quotation_rejected',
  APPOINTMENT_SCHEDULED: 'appointment_scheduled',
  APPOINTMENT_CHANGED: 'appointment_changed',
  APPOINTMENT_CANCELLED: 'appointment_cancelled',
  REPAIR_STATUS_UPDATED: 'repair_status_updated',
  OWNER_APPROVAL_REQUIRED: 'owner_approval_required',
  PART_REQUIRED: 'part_required',
  REPAIR_COMPLETED: 'repair_completed',
  WARRANTY_CREATED: 'warranty_created',
  WARRANTY_CLAIM_UPDATED: 'warranty_claim_updated',
  DONATION_MATCH: 'donation_match',
  DONATION_ACCEPTED: 'donation_accepted',
  DONATION_OFFER_CREATED: 'donation_offer_created',
  DONATION_OFFER_ACCEPTED: 'donation_offer_accepted',
  DONATION_HANDOVER_SCHEDULED: 'donation_handover_scheduled',
  DONATION_ITEM_RECEIVED: 'donation_item_received',
  DONATION_INSPECTION_COMPLETED: 'donation_inspection_completed',
  DONATION_NEED_MATCHED: 'donation_need_matched',
  DONATION_NEED_FULFILLED: 'donation_need_fulfilled',
  IMPACT_RECORD_CREATED: 'impact_record_created',
  PICKUP_SCHEDULED: 'pickup_scheduled',
  HANDOVER_COMPLETED: 'handover_completed',
  REVIEW_RECEIVED: 'review_received',
  DISPUTE_OPENED: 'dispute_opened',
  DISPUTE_RESOLVED: 'dispute_resolved',
  NEW_MESSAGE: 'new_message',
  FORUM_REPLY: 'forum_reply',
  FORUM_ACCEPTED: 'forum_accepted',
  FORUM_REPORT_UPDATED: 'forum_report_updated',
};

const MODERATION_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  FLAGGED: 'flagged',
  REMOVED: 'removed',
};

const SEVERITY = {
  UNKNOWN: 'unknown',
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
};

const ADMIN_PERMISSIONS = {
  SUPPORT: 'support',
  VERIFICATION: 'verification',
  SAFETY: 'safety',
  DISPUTES: 'disputes',
  CONFIG: 'config',
  AUDIT: 'audit',
  SUPER_ADMIN: 'super_admin',
};

const REVIEW_QUEUE_TYPE = {
  VERIFICATION: 'verification',
  SAFETY_FLAG: 'safety_flag',
  DISPUTE: 'dispute',
  STALLED_REQUEST: 'stalled_request',
  USER_APPEAL: 'user_appeal',
  SYSTEM_HEALTH: 'system_health',
};

const REVIEW_QUEUE_STATE = {
  PENDING: 'pending',
  IN_REVIEW: 'in_review',
  ESCALATED: 'escalated',
  SNOOZED: 'snoozed',
  RESOLVED: 'resolved',
};

const REVIEW_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
};

const DISPUTE_RESOLUTIONS = {
  FULL_RESOLUTION: 'full_resolution',
  PARTIAL_SETTLEMENT: 'partial_settlement',
  FREE_REWORK: 'free_rework',
  WARRANTY_ENFORCED: 'warranty_enforced',
  MUTUAL_CLOSURE: 'mutual_closure',
};

const SAFETY_PATTERN_TYPE = {
  KEYWORD: 'keyword',
  REGEX: 'regex',
};

module.exports = {
  ROLES,
  ACCOUNT_STATUS,
  ORGANIZATION_TYPES,
  VERIFICATION_STATUS,
  JOB_PART_STATUS,
  ITEM_CONDITION,
  ITEM_STATUS,
  PATHWAYS,
  REPAIR_REQUEST_STATUS,
  REPAIR_STATUS_TRANSITIONS,
  QUOTATION_STATUS,
  APPOINTMENT_STATUS,
  APPOINTMENT_TYPE,
  REPAIR_JOB_STATUS,
  REPAIR_JOB_TRANSITIONS,
  DONATION_STATUS,
  DONATION_TRANSITIONS,
  COMMUNITY_NEED_STATUS,
  INSPECTION_OUTCOMES,
  PROCESSING_OUTCOMES,
  HUB_STATUS,
  DISPUTE_STATUS,
  DISPUTE_CATEGORIES,
  DISPUTE_RESOLUTIONS,
  WARRANTY_STATUS,
  PART_STATUS,
  PART_CONDITION,
  RISK_LEVEL,
  SERVICE_METHOD,
  NOTIFICATION_TYPES,
  MODERATION_STATUS,
  SEVERITY,
  ADMIN_PERMISSIONS,
  REVIEW_QUEUE_TYPE,
  REVIEW_QUEUE_STATE,
  REVIEW_PRIORITY,
  SAFETY_PATTERN_TYPE,
};

